spring.application.name=labo6final

spring.datasource.url=jdbc:mysql://localhost:3306/clinica_app?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&noTimezoneConversionForTimeType=true&connectionTimeZone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# SpringDoc OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

spring.profiles.active=local

firebase.service-account=file:D:/gonzalo/PUI/ProyectoFinalL6/api_clinica_app/clinica-app.json
firebase.project-id=clinica-app-41f1a